username: GitHub-CI
icon_url: https://octodex.github.com/images/mona-the-rivetertocat.png

pretext: Triggered via {{eventName}} by {{actor}} {{or action "action"}} {{ref}} `{{diffRef}}`
title: GitHub Actions
title_link: https://support.github.com

text: |
  *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
  {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
  {{#if payload.commits}}
  *Commits*
  {{#each payload.commits}}
  <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
  {{/each}}
  {{/if}}

fallback: |-
  [GitHub] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}

fields:
  - title: Job Steps
    value: "{{#each jobSteps}}{{icon this.outcome}} {{@key}}\n{{/each}}"
    short: false
  - title: Workflow
    value: "<{{workflowUrl}}|{{workflow}}>"
    short: true
  - title: Git Ref
    value: "{{ref}} ({{refType}})"
    short: true
  - title: Run ID
    value: |-
      <{{workflowRunUrl}}|{{runId}}>
    short: true
  - title: Run Number
    value: "{{runNumber}}"
    short: true
  - title: Actor
    value: "{{actor}}"
    short: true
  - title: Job Status
    value: "{{jobStatus}}"
    short: true
    
 # fields
  - type: section
    fields:
    - type: mrkdwn
      text: |-
        *Job Steps*
        {{#each jobSteps}}{{#ifneq this.outcome 'skipped'}}{{icon this.outcome}}  {{@key}}
        {{/ifneq}}{{/each}}
  - type: section
    fields:
    - type: mrkdwn
      text: "*Workflow*\n<{{{workflowUrl}}}|{{workflow}}>"
    - type: mrkdwn
      text: "*Git Ref*\n{{ref}} ({{refType}})"
    - type: mrkdwn
      text: |-
        *Run ID*
        <{{workflowRunUrl}}|{{runId}}>
    - type: mrkdwn
      text: "*Run Number*\n{{runNumber}}"
    - type: mrkdwn
      text: "*Actor*\n{{actor}}"
    - type: mrkdwn
      text: "*Job Status*\n{{jobStatus}}"

footer: >-
  <{{repositoryUrl}}|{{repositoryName}}> {{workflow}} #{{runNumber}}

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'
