name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
      
=======
>>>>>>> 0a8ee2b449f2d5a9360a78dc43160562df033fda
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          # channel: '#githubaction-test'
          config: .github/slack.yml
        if: always()
