name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - name: Ckeckout Repository
        uses: actions/checkout@v2

      - name: Starting
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#githubaction-test'
          config: .github/slack.yml
        if: always()
        
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: nginx-app.pkr.hcl

      - name: Ending
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#githubaction-test'
          config: .github/slack.yml
        if: always()
