name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - name: ckeckout source code
        uses: actions/checkout@v2
        
      - name: Starting
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          message: Starting Build and Push...
        if: always()
        
      - name: Build
        id: build
        run: |
          npm install
          npm run build
        
      - name: Ending
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          config: .github/slack-config.yml
        if: always()
