name: Packer CICD 
on:
  push:
    branches: [ "main" ]
 
jobs:
  packer-cicd:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - name: ckeckout source code
        uses: actions/checkout@v3
        
      - name: Starting slack alert
        uses: act10ns/slack@v1
        with: 
          status: starting
          config: .github/slack.yml
        if: always()

      - name: Setup packer
        uses: hashicorp/setup-packer@main
        id: packer-setup
        with:
          version: "1.8.3" # or `latest`

      - name: Packer init
        id: packer-init
        run: "packer init ."

      - name: Packer validate
        id: packer-validate
        run: "packer validate ."

      - name: Packer build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
        id: packer-build
        run: "packer build nginx-app.pkr.hcl"
                  
      - name: Ending slack alert
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          config: .github/slack.yml
        if: always()
