name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - uses: actions/checkout@v2

      - name: Starting
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#githubaction-test'
          config: .github/slack.yml
        if: always()

      - name: Ending
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#githubaction-test'
          config: .github/slack.yml
        if: always()