name: Testing slack message
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  test-jobs:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - name: ckeckout source code
        uses: actions/checkout@v2
        
      - name: Starting
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          config: .github/slack.yml
        if: always()
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
                  
      - name: Ending
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          config: .github/slack.yml
        if: always()
