name: Packer CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#githubaction-test'
          message: Starting the cicd pipeline....
        if: always()

      - name: Ckeckout Repository
        uses: actions/checkout@v3

      - name: Initialize Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: nginx-app.pkr.hcl

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: nginx-app.pkr.hcl

      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: nginx-app.pkr.hcl
          working_directory: .
        env:
          PACKER_LOG: 1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubaction-test'
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}