name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
   
    steps:
      - name: Starting Slack Notification
        uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#githubaction-test'
          pretext: Triggered via {{eventName}} by {{actor}} {{ref}} `{{defRef}}`
          title: Github Actions
          
          text: |
             *<{{workflowRunUrl}}|Workflow _{{workflow}}_ job _{{jobName}}_ triggered by _{{eventName}}_ is _{{jobStatus}}_>* for <{{refUrl}}|`{{ref}}`>
              {{#if description}}<{{diffUrl}}|`{{diffRef}}`> - {{description}}{{/if}}
              {{#if payload.commits}}
              *Commits*
              {{#each payload.commits}}
              <{{this.url}}|`{{truncate this.id 8}}`> - {{this.message}}
              {{/each}}
              {{/if}}

          fallback: |-
            [Github] {{workflow}} #{{runNumber}} {{jobName}} is {{jobStatus}}         
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubaction-test'
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}