name: Deploy Services into Duplo EKS cluster
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  deploy_image:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
   
    steps:
      - name: Starting Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          # channel: '#githubaction-test'
          config: .github/slack.yml
          # message: Test
        # if: always()

      - name: test
        run: cat .github/slack.yml